<template>
  <div id="main" style="width: 1200px; height: 800px;overflow: auto;"></div>
  <button @click="initMap">生成地图</button>
</template>
<script lang="ts">
import * as echarts from 'echarts'
import geo from '@/map/uk.geo.json'
export default {
  setup() {
    const initMap = () => {
      //  需求： 11张饼图  1张热力图
      // 基于准备好的dom，初始化echarts实例
      const myChart = echarts.init(document.getElementById('main'))
      console.log(myChart)
      // 绘制图表
      echarts.registerMap('UnitedKindom', geo)
      myChart.setOption({
        geo: [
          {
            map: 'UnitedKindom',
            aspectScale: 0.75,
            zoom: 1,
          },
        ],
        title: {
          text: 'Creative Industries by Region',
          left: 'center',
          top: 50,
          textStyle: {
            fontSize: 25
          }
        },
        visualMap: {
          // min: 0,
          // max: 100000,
          type: 'piecewise',
          // splitNumber: 20,
          // inRange: {
          //   color: ['lightskyblue', 'yellow', 'orangered']
          // },
          left: 200,
          bottom: 100,
          pieces:[
            {min: 0, max:1000, label: '0 - 1000', color: 'lightskyblue'},
            {min: 1000, max:10000, label: '1000 - 10000', color: 'yellow'},
            {min: 10000, max:100000, label: '10000 - 100000', color: 'orangered'},
          ]
        },
        series: [
          {
            type: 'map',
            map: 'UnitedKindom',
            data: [
              {name: 'Scotland', value: 12455},
              {name: 'Wales', value: 5960},
              {name: 'Northern Ireland', value: 3190},
              {name: 'Yorkshire and The Humber', value: 13170},
              {name: 'North East', value: 4510},
              {name: 'North West', value: 19730},
              {name: 'South West', value: 21010},
              {name: 'South East', value: 53970},
              {name: 'East Midlands', value: 12410},
              {name: 'West Midlands', value: 15335},
              {name: 'East', value: 26505},
              {name: 'London', value: 98150},
            ],
            nameMap: {
              'Dumfries and Galloway': 'Scotland',
              'Scottish Borders': 'Scotland',
              'Midlothian': 'Scotland',
              'East Lothian': 'Scotland',
              'Edinburgh': 'Scotland',
              'West Lothian': 'Scotland',
              'South Lanarkshire': 'Scotland',
              'East Ayrshire': 'Scotland',
              'South Ayrshire': 'Scotland',
              'North Ayrshire': 'Scotland',
              'Inverclyde': 'Scotland',
              'Renfrewshire': 'Scotland',
              'East Renfrewshire': 'Scotland',
              'Glasgow': 'Scotland',
              'North Lanarkshire': 'Scotland',
              'Falkirk': 'Scotland',
              'East Dunbartonshire': 'Scotland',
              'West Dunbartonshire': 'Scotland',
              'Argyll and Bute': 'Scotland',
              'Stirling': 'Scotland',
              'Clackmannanshire': 'Scotland',
              'Fife': 'Scotland',
              'Dundee': 'Scotland',
              'Angus': 'Scotland',
              'Perth and Kinross': 'Scotland',
              'Perthshire and Kinross': 'Scotland',
              'Aberdeenshire': 'Scotland',
              'Aberdeen': 'Scotland',
              'Moray': 'Scotland',
              'Highland': 'Scotland',
              'Eilean Siar': 'Scotland',
              'Orkney': 'Scotland',
              'Shetland': 'Scotland',
              'North Ayshire': 'Scotland',
              'Isle of Anglesey': 'Wales',
              'Gwynedd': 'Wales',
              'Conwy': 'Wales',
              'Denbighshire': 'Wales',
              'Flintshire': 'Wales',
              'Wrexham': 'Wales',
              'Ceredigion': 'Wales',
              'Powys': 'Wales',
              'Pembrokeshire': 'Wales',
              'Carmarthenshire': 'Wales',
              'Swansea': 'Wales',
              'Neath Port Talbot': 'Wales',
              'Bridgend': 'Wales',
              'Rhondda Cynon Taf	': 'Wales',
              'Merthyr Tydfil': 'Wales',
              'Caerphilly': 'Wales',
              'Blaenau Gwent': 'Wales',
              'Torfaen': 'Wales',
              'Monmouthshire': 'Wales',
              'Vale of Glamorgan': 'Wales',
              'Cardiff': 'Wales',
              'Anglesey': 'Wales',
              'Newport': 'Wales',
              'Rhondda, Cynon, Taff': 'Wales',
              'Ards': 'Northern Ireland',
              'Castlereagh': 'Northern Ireland',
              'Down': 'Northern Ireland',
              'North Down': 'Northern Ireland',
              'Banbridge': 'Northern Ireland',
              'Belfast': 'Northern Ireland',
              'Lisburn': 'Northern Ireland',
              'Antrim': 'Northern Ireland',
              'Ballymena': 'Northern Ireland',
              'Ballymoney': 'Northern Ireland',
              'Carrickfergus': 'Northern Ireland',
              'Larne': 'Northern Ireland',
              'Moyle': 'Northern Ireland',
              'Newtownabbey': 'Northern Ireland',
              'Armagh': 'Northern Ireland',
              'Craigavon': 'Northern Ireland',
              'Newry and Mourne': 'Northern Ireland',
              'Coleraine': 'Northern Ireland',
              'Magherafelt': 'Northern Ireland',
              'Derry': 'Northern Ireland',
              'Limavady': 'Northern Ireland',
              'Cookstown': 'Northern Ireland',
              'Dungannon': 'Northern Ireland',
              'Omagh': 'Northern Ireland',
              'Strabane': 'Northern Ireland',
              'Fermanagh': 'Northern Ireland',
              'South Yorkshire': 'Yorkshire and The Humber',
              'West Yorkshire': 'Yorkshire and The Humber',
              'East Riding of Yorkshire': 'Yorkshire and The Humber',
              'Sheffield': 'Yorkshire and The Humber',
              'Rotherham': 'Yorkshire and The Humber',
              'Barnsley': 'Yorkshire and The Humber',
              'Doncaster': 'Yorkshire and The Humber',
              'Wakefield': 'Yorkshire and The Humber',
              'Kirklees': 'Yorkshire and The Humber',
              'Calderdale': 'Yorkshire and The Humber',
              'Bradford': 'Yorkshire and The Humber',
              'Leeds': 'Yorkshire and The Humber',
              'York': 'Yorkshire and The Humber',
              'Kingston upon Hull': 'Yorkshire and The Humber',
              'North Lincolnshire': 'Yorkshire and The Humber',
              'North East Lincolnshire': 'Yorkshire and The Humber',
              'North Yorkshire': 'Yorkshire and The Humber',
              'Northumberland': 'North East',
              'County Durham': 'North East',
              'Tyne and Wear': 'North East',
              'Durham': 'North East',
              'Darlington': 'North East',
              'Hartlepool': 'North East',
              'Stockton-on-Tees': 'North East',
              'Middlesbrough': 'North East',
              'Redcar and Cleveland': 'North East',
              'South Tyneside': 'North East',
              'Sunderland': 'North East',
              'North Tyneside': 'North East',
              'Gateshead': 'North East',
              'Newcastle upon Tyne': 'North East',
              'Cumbria': 'North West',
              'Lancashire': 'North West',
              'Merseyside': 'North West',
              'Greater Manchester': 'North West',
              'Cheshire': 'North West',
              'Blackburn with Darwen': 'North West',
              'Blackpool': 'North West',
              'Halton': 'North West',
              'Warrington': 'North West',
              'Sefton': 'North West',
              'Liverpool': 'North West',
              'Wigan': 'North West',
              'Knowsley': 'North West',
              'Bolton': 'North West',
              'Bury': 'North West',
              'Rochdale': 'North West',
              'Oldham': 'North West',
              'Tameside': 'North West',
              'Manchester': 'North West',
              'Trafford': 'North West',
              'Cheshire East': 'North West',
              'Cheshire West and Chester': 'North West',
              'Salford': 'North West',
              'Stockport': 'North West',
              'Gloucestershire': 'South West',
              'Wiltshire': 'South West',
              'Somerset': 'South West',
              'Dorset': 'South West',
              'Devon': 'South West',
              'Cornwall': 'South West',
              'Cornwall and Isles of Scilly': 'South West',
              'Avon': 'South West',
              'South Gloucestershire': 'South West',
              'Bristol': 'South West',
              'Swindon': 'South West',
              'Bath and North East Somerset': 'South West',
              'North Somerset': 'South West',
              'Poole': 'South West',
              'Plymouth': 'South West',
              'Torbay': 'South West',
              'Buckinghamshire': 'South East',
              'Oxfordshire': 'South East',
              'Surrey': 'South East',
              'Kent': 'South East',
              'East Sussex': 'South East',
              'West Sussex': 'South East',
              'Hampshire': 'South East',
              'Portsmouth': 'South East',
              'Southampton': 'South East',
              'Milton Keynes': 'South East',
              'Brighton and Hove': 'South East',
              'Reading': 'South East',
              'West Berkshire': 'South East',
              'Wokingham': 'South East',
              'Bracknell Forest': 'South East',
              'Royal Borough of Windsor and Maidenhead': 'South East',
              'Slough': 'South East',
              'Isle of Wight': 'South East',
              'Medway': 'South East',
              'Leicester': 'East Midlands',
              'Leicestershire': 'East Midlands',
              'Derbyshire': 'East Midlands',
              'Derby': 'East Midlands',
              'Nottingham': 'East Midlands',
              'Lincolnshire': 'East Midlands',
              'Northamptonshire': 'East Midlands',
              'Rutland': 'East Midlands',
              'Nottinghamshire': 'East Midlands',
              'Shropshire': 'West Midlands',
              'Warwickshire': 'West Midlands',
              'Herefordshire': 'West Midlands',
              'Staffordshire': 'West Midlands',
              'Worcestershire': 'West Midlands',
              'Birmingham': 'West Midlands',
              'Sandwell': 'West Midlands',
              'Dudley': 'West Midlands',
              'Wolverhampton': 'West Midlands',
              'Walsall': 'West Midlands',
              'Solihull': 'West Midlands',
              'Coventry': 'West Midlands',
              'Stoke-on-Trent': 'West Midlands',
              'Telford and Wrekin': 'West Midlands',
              'Hertfordshire': 'East',
              'Cambridgeshire': 'East',
              'Essex': 'East',
              'Norfolk': 'East',
              'Thurrock': 'East',
              'Southend-on-Sea': 'East',
              'Central Bedfordshire': 'East',
              'Bedford': 'East',
              'Peterborough': 'East',
              'Suffolk': 'East',
              'Luton': 'East',
              'Barking and Dagenham': 'London',
              'Bexley': 'London',
              'Bromley': 'London',
              'Brent': 'London',
              'Camden': 'London',
              'Ealing': 'London',
              'Enfield': 'London',
              'Greenwich': 'London',
              'Hammersmith and Fulham': 'London',
              'Hounslow': 'London',
              'Islington': 'London',
              'Kensington and Chelsea': 'London',
              'Croydon': 'London',
              'Merton': 'London',
              'Redbridge': 'London',
              'Richmond upon Thames': 'London',
              'Sutton': 'London',
              'Tower Hamlets': 'London',
              'Waltham Forest': 'London',
              'Wandsworth': 'London',
              'Westminster': 'London',
              'Havering': 'London',
              'Hillingdon': 'London',
              'Kingston upon Thame': 'London',
              'Hackney': 'London',
              'Haringey': 'London',
              'Harrow': 'London',
              'Lambeth': 'London',
              'Lewisham': 'London',
              'Newham': 'London',
              'Southwark': 'London',
              'City': 'London',
              'Barnet': 'London',
            }
          }
        ]
      })
    }
    return {
      initMap,
    }
  },
}
</script>
<style scoped></style>
